"""initial migration with table images

Revision ID: 65e4f0ce802e
Revises:
Create Date: 2024-10-16 01:14:23.690684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65e4f0ce802e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("depth", sa.Float(), nullable=True),
        sa.Column("pixels", sa.ARRAY(sa.Integer()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index('ix_images_depth', 'images', ['depth'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_depth', table_name='images')
    op.drop_table("images")
    # ### end Alembic commands ###
